/** Public Node-only cross-client Runtime acceptance fixture. */

export {
  assertCrossClientLifecycle,
  createCrossClientFixture,
  CrossClientFixtureAdapterError,
  CrossClientFixtureClosedError,
  CrossClientFixtureOperationError,
  CrossClientFixtureSetupError,
  type CrossClientAppAdapter,
  type CrossClientAppAdapters,
  type CrossClientAppContext,
  type CrossClientAppHandle,
  type CrossClientCliAdapter,
  type CrossClientCliResult,
  type CrossClientDashboardApiAdapter,
  type CrossClientDashboardApiHandle,
  type CrossClientFileSystemAdapter,
  type CrossClientFixture,
  type CrossClientFixtureDependencies,
  type CrossClientFixtureOptions,
  type CrossClientLifecycleEvent,
  type CrossClientLifecycleSnapshot,
  type CrossClientMockOptions,
  type CrossClientMockServerAdapter,
  type CrossClientMockServerHandle,
  type CrossClientMockServerInput,
  type CrossClientObservation,
  type CrossClientRuntimeClient,
  type CrossClientRuntimeExit,
  type CrossClientRuntimeHealthAdapter,
  type CrossClientRuntimeHealthInput,
  type CrossClientRuntimeProcessAdapter,
  type CrossClientRuntimeProcessHandle,
  type CrossClientRuntimeProcessInput,
  type CrossClientStateClient,
} from './cross-client-fixture.ts'
