/** Private cross-process rollback executor for verified native Desktop installers. */

import { createHash, randomUUID } from 'node:crypto'
import { execFileSync, spawn, type ChildProcess } from 'node:child_process'
import { constants, readFileSync, type Stats } from 'node:fs'
import { chmod, copyFile, lstat, mkdtemp, open, readdir, rename, rm, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, extname, isAbsolute, join, posix, win32 } from 'node:path'

const parentExitPollMs = 100

/**
 * One process identity that rejects a recycled numeric process identifier.
 * The creation bound is generated by the process itself before it launches a detached worker.
 */
export interface NativeProcessReference {
  /** Operating-system process identifier. */
  readonly processId: number
  /** Absolute executable or launcher path associated with the expected process. */
  readonly executablePath: string
  /** Epoch millisecond upper bound for the expected process creation time. */
  readonly startedBeforeMs: number
  /** Linux kernel start-time token, retained when an AppImage launcher can `exec` into a mounted payload. */
  readonly linuxStartTicks?: string
  /** POSIX process-group identifier created for a detached candidate launch. */
  readonly processGroupId?: number
}

/** One private rollback request handed from Main to its detached local worker. */
export interface NativeRollbackPlan {
  /** Wire version for the detached local worker. */
  readonly schemaVersion: 1
  /** Native platform that selects a verifier-approved installer operation. */
  readonly platform: 'win32' | 'darwin' | 'linux'
  /** Main process that must exit before any installed bytes are replaced. */
  readonly parentProcess: NativeProcessReference
  /** Current packaged executable used only to relaunch the restored application. */
  readonly applicationPath: string
  /** AppImage path when the running Linux package is a self-contained AppImage. */
  readonly appImagePath?: string
  /** Locally cached, manifest-verified rollback artifact. */
  readonly rollbackArtifactPath: string
  /** SHA-256 digest that authenticates the local rollback artifact again before execution. */
  readonly rollbackSha256: string
  /** Native rollback installer format tied to the current platform. */
  readonly rollbackFormat: 'nsis' | 'zip' | 'appimage'
  /** Policy-selected candidate Dashboard health window that also bounds the safe shutdown handoff. */
  readonly healthCheckTimeoutMs: number
  /** Transaction identifier when this rollback settles a retained native-update journal. */
  readonly transactionId?: string
}

/** One detached watchdog request that rolls back a candidate which never becomes healthy. */
export interface NativeUpdateWatchPlan extends NativeRollbackPlan {
  /** Locally cached, manifest-verified candidate installer that this external worker installs itself. */
  readonly candidateArtifactPath: string
  /** SHA-256 digest that the worker rechecks immediately before candidate installation. */
  readonly candidateSha256: string
  /** Candidate installer format, fixed by the selected native platform. */
  readonly candidateFormat: 'nsis' | 'zip' | 'appimage'
  /** Exact private journal written by the native-install adapter. */
  readonly journalPath: string
  /** Candidate version that must be acknowledged before this watchdog exits harmlessly. */
  readonly candidateVersion: string
  /** Bounded time allowed for the candidate to load its authenticated Dashboard. */
  readonly healthCheckTimeoutMs: number
  /** Immutable transaction identifier that binds this watcher to one journal generation. */
  readonly transactionId: string
}

/** Native process, file, and clock collaborators isolated for rollback tests. */
export interface NativeRollbackOperations {
  /** @param process - expected Main or candidate process. @returns whether this exact process is still alive. */
  isProcessAlive(process: NativeProcessReference): boolean
  /** @param process - unhealthy candidate Main process. @returns after a checked platform termination request. */
  terminate(process: NativeProcessReference): void
  /** @param process - candidate that ignored a graceful termination request. @returns after a checked forceful termination request. */
  forceTerminate(process: NativeProcessReference): void
  /** @returns monotonic wall-clock milliseconds used only for the bounded watchdog deadline. */
  now(): number
  /** @param milliseconds - bounded polling delay. @returns fulfillment after the delay. */
  delay(milliseconds: number): Promise<void>
  /** @param path - locally cached artifact. @returns bytes used for digest validation. */
  readArtifact(path: string): Promise<Uint8Array>
  /**
   * @param sourcePath - authenticated cache path.
   * @param bytes - verified installer bytes.
   * @returns private executable or archive copy used exactly once.
   */
  snapshotArtifact(sourcePath: string, bytes: Uint8Array): Promise<NativeArtifactSnapshot>
  /**
   * @param path - private native-update journal.
   * @returns validated watchdog state, or undefined only when the journal was removed unexpectedly.
   */
  readWatchState(path: string): Promise<NativeUpdateWatchState | undefined>
  /**
   * @param path - transaction-specific worker heartbeat.
   * @param content - exact transaction-bound worker liveness record.
   * @returns settlement after exclusive durable publication.
   */
  writeWatchHeartbeat(path: string, content: string): Promise<void>
  /**
   * @param path - transaction-specific rollback completion marker.
   * @param content - exact transaction record.
   * @returns settlement after exclusive durable publication.
   */
  writeRollbackCompletion(path: string, content: string): Promise<void>
  /** @param command - absolute executable path. @param args - fixed native updater arguments. @returns exit settlement. */
  run(command: string, args: readonly string[]): Promise<void>
  /**
   * @param command - restored or candidate application executable.
   * @returns exact detached process identity after launch ownership transfers.
   */
  launch(command: string): NativeProcessReference
  /** @param prefix - staging-directory prefix on the destination volume. @returns created private staging directory. */
  mkdtemp(prefix: string): Promise<string>
  /** @param path - directory to enumerate. @returns direct native entries. */
  readdir(path: string): Promise<readonly NativeDirectoryEntry[]>
  /** @param from - source path. @param to - destination path. @returns settlement after an atomic same-volume move. */
  rename(from: string, to: string): Promise<void>
  /** @param from - source artifact. @param to - exact temporary replacement path. @returns settlement after a byte copy. */
  copyFile(from: string, to: string): Promise<void>
  /** @param path - replacement AppImage path. @param mode - exact executable mode. @returns settlement after mode repair. */
  chmod(path: string, mode: number): Promise<void>
  /** @param path - candidate replacement. @returns filesystem metadata used to reject directories. */
  stat(path: string): Promise<{ readonly isFile: () => boolean }>
  /** @param path - exact private staging or retained path. @returns fulfillment when absent or removed. */
  remove(path: string): Promise<void>
}

/** Minimal journal state relevant to a detached watchdog. */
export interface NativeUpdateWatchState {
  /** Lifecycle phase written by the Main-owned native installer adapter. */
  readonly phase: 'awaiting-dashboard-health' | 'dashboard-health-checking' | 'rollback-scheduled' | 'applied'
  /** Candidate version associated with this one native installer transaction. */
  readonly version: string
  /** Immutable transaction identifier associated with this one native installer transaction. */
  readonly transactionId: string
  /** Candidate Main process after it has reached the first health-check write; retained through application acknowledgement. */
  readonly candidateProcess?: NativeProcessReference
}

/** Terminal result of one detached candidate watchdog. */
export type NativeUpdateWatchOutcome = 'applied' | 'rolled-back' | 'unchanged'

/** Direct directory information required by the macOS zip extraction path. */
export interface NativeDirectoryEntry {
  /** Basename without a parent path. */
  readonly name: string
  /** @returns whether this entry is a directory. */
  isDirectory(): boolean
}

/** One private worker-owned copy of an already verified native installer. */
export interface NativeArtifactSnapshot {
  /** Absolute private installer copy passed to a local native installer or replacement operation. */
  readonly path: string
  /** Removes the private copy after the installer operation has stopped using it. */
  dispose(): Promise<void>
}

/**
 * Private installer copies retained by a detached worker before Main is permitted to exit.
 * The worker owns disposal so a recovery path never has to reopen the mutable updater cache.
 */
export interface PreparedNativeRollbackArtifacts {
  /** Verified stable installer copy used for every rollback path in this transaction. */
  readonly rollback: NativeArtifactSnapshot
  /** Verified candidate installer copy when the worker is supervising an update. */
  readonly candidate?: NativeArtifactSnapshot
  /** Releases all worker-owned private copies after the worker reaches a terminal outcome. */
  dispose(): Promise<void>
}

/**
 * Execute exactly one verified rollback after the failed Main process exits.
 * @param plan - authenticated local installer and current installation information.
 * @param operations - native side effects; production defaults run only fixed local commands.
 * @param prepared - worker-owned snapshots already retained before Main exited.
 * @returns fulfillment after the restored application has been launched.
 */
export async function executeNativeRollback(
  plan: NativeRollbackPlan,
  operations: NativeRollbackOperations = nativeRollbackOperations,
  prepared?: PreparedNativeRollbackArtifacts,
  beforeStableLaunch?: () => Promise<void>,
): Promise<void> {
  validatePlan(plan)
  if (!await waitForParentExit(plan.parentProcess, plan.healthCheckTimeoutMs, operations)) {
    throw new Error('native rollback current application did not exit before the safe handoff deadline')
  }
  const rollback = prepared?.rollback ?? await snapshotVerifiedRollbackArtifact(plan, operations)
  try {
    if (plan.platform === 'win32') {
      await operations.run(rollback.path, ['/S'])
      await beforeStableLaunch?.()
      operations.launch(plan.applicationPath)
      return
    }
    if (plan.platform === 'darwin') {
      await restoreMacZip(rollback.path, plan.applicationPath, operations)
      await beforeStableLaunch?.()
      operations.launch(plan.applicationPath)
      return
    }
    await restoreLinuxAppImage(rollback.path, plan, operations)
    await beforeStableLaunch?.()
    operations.launch(plan.appImagePath ?? plan.applicationPath)
  } finally {
    if (prepared === undefined) await rollback.dispose()
  }
}

/**
 * Supervise a scheduled native update outside the candidate application process.
 * @param plan - verified rollback artifact and private health journal.
 * @param operations - detached-process effects; defaults never consume remote release data.
 * @param prepared - worker-owned snapshots already retained before Main exited.
 * @returns fulfillment after health succeeds, a manual rollback supersedes this worker, or rollback relaunches the stable app.
 */
export async function superviseNativeUpdate(
  plan: NativeUpdateWatchPlan,
  operations: NativeRollbackOperations = nativeRollbackOperations,
  prepared?: PreparedNativeRollbackArtifacts,
): Promise<NativeUpdateWatchOutcome> {
  if (prepared === undefined) await verifyNativeRollbackReadiness(plan, operations)
  else {
    validateWatchPlan(plan)
    if (prepared.candidate === undefined) throw new Error('native update watchdog is missing its prepared candidate installer')
  }
  if (!await waitForParentExitBeforeCandidate(plan.parentProcess, plan.healthCheckTimeoutMs, operations)) return 'unchanged'
  let beforeInstall: NativeUpdateWatchState
  try {
    const state = await operations.readWatchState(plan.journalPath)
    if (state === undefined) throw new Error('native update watchdog journal disappeared before candidate installation')
    if (state.version !== plan.candidateVersion || state.transactionId !== plan.transactionId) {
      throw new Error('native update watchdog journal transaction changed before candidate installation')
    }
    beforeInstall = state
  } catch {
    await executeWatchedRollback(plan, operations, prepared)
    return 'rolled-back'
  }
  if (beforeInstall.phase === 'applied') return 'applied'
  if (beforeInstall.phase !== 'awaiting-dashboard-health') {
    await terminateJournalCandidate(beforeInstall, plan.healthCheckTimeoutMs, operations)
    await executeWatchedRollback(plan, operations, prepared)
    return 'rolled-back'
  }
  let candidateProcess: NativeProcessReference | undefined
  try {
    candidateProcess = await installNativeCandidate(plan, operations, prepared?.candidate)
  } catch {
    await executeWatchedRollback(plan, operations, prepared)
    return 'rolled-back'
  }
  if (candidateProcess === undefined) {
    operations.launch(stableApplicationPath(plan))
    return 'unchanged'
  }
  try {
    await writeNativeWatchHeartbeat(plan, operations)
  } catch {
    if (operations.isProcessAlive(candidateProcess)) {
      await terminateCandidateBeforeRollback(candidateProcess, plan.healthCheckTimeoutMs, operations)
    }
    await executeWatchedRollback(plan, operations, prepared)
    return 'rolled-back'
  }
  const deadline = operations.now() + plan.healthCheckTimeoutMs
  while (operations.now() < deadline) {
    let state: NativeUpdateWatchState | undefined
    try {
      state = await operations.readWatchState(plan.journalPath)
      if (state === undefined) throw new Error('native update watchdog journal disappeared before health acknowledgement')
      if (state.version !== plan.candidateVersion || state.transactionId !== plan.transactionId) {
        throw new Error('native update watchdog journal transaction changed')
      }
    } catch {
      break
    }
    if (state.phase === 'dashboard-health-checking') {
      const reported = state.candidateProcess
      if (reported === undefined || !matchesLaunchedCandidate(plan.platform, candidateProcess, reported)) break
      candidateProcess = {
        ...reported,
        ...(candidateProcess.processGroupId === undefined ? {} : { processGroupId: candidateProcess.processGroupId }),
      }
    }
    if (state.phase === 'applied') {
      const reported = state.candidateProcess
      if (reported !== undefined && matchesLaunchedCandidate(plan.platform, candidateProcess, reported)) return 'applied'
      break
    }
    if (state.phase === 'rollback-scheduled') return 'unchanged'
    if (!operations.isProcessAlive(candidateProcess)) break
    await operations.delay(parentExitPollMs)
  }
  if (operations.isProcessAlive(candidateProcess)) {
    await terminateCandidateBeforeRollback(candidateProcess, plan.healthCheckTimeoutMs, operations)
  }
  await executeWatchedRollback(plan, operations, prepared)
  return 'rolled-back'
}

async function executeWatchedRollback(
  plan: NativeUpdateWatchPlan,
  operations: NativeRollbackOperations,
  prepared?: PreparedNativeRollbackArtifacts,
): Promise<void> {
  await executeNativeRollback(plan, operations, prepared, async () => {
    await operations.writeRollbackCompletion(
      nativeUpdateRolledBackPath(plan.rollbackArtifactPath, plan.transactionId, plan.platform),
      `${plan.transactionId}\n`,
    )
  })
}

/**
 * Verify all local bytes and persisted state before a detached worker reports readiness to Main.
 * @param plan - private rollback or watchdog request.
 * @param operations - native filesystem and process collaborators.
 * @returns fulfillment only when the worker can safely begin supervising the requested transition.
 */
export async function verifyNativeRollbackReadiness(
  plan: NativeRollbackPlan | NativeUpdateWatchPlan,
  operations: NativeRollbackOperations = nativeRollbackOperations,
): Promise<void> {
  if (isWatchPlan(plan)) {
    validateWatchPlan(plan)
    const state = await operations.readWatchState(plan.journalPath)
    if (state === undefined || state.version !== plan.candidateVersion || state.transactionId !== plan.transactionId
      || state.phase !== 'awaiting-dashboard-health') {
      throw new Error('native update watchdog journal is not ready')
    }
  } else {
    validatePlan(plan)
  }
  await verifyRollbackArtifact(plan, operations)
  if (isWatchPlan(plan)) await verifyCandidateArtifact(plan, operations)
  await verifyNativeInstallationDestination(plan, operations)
}

/**
 * Copy every verified installer into worker-owned private storage before Main exits.
 * @param plan - fixed local rollback or update-watch operation.
 * @param operations - native filesystem collaborators used for validation and private snapshots.
 * @returns retained copies that can execute without reopening the native-update cache.
 */
export async function prepareNativeRollbackArtifacts(
  plan: NativeRollbackPlan | NativeUpdateWatchPlan,
  operations: NativeRollbackOperations = nativeRollbackOperations,
): Promise<PreparedNativeRollbackArtifacts> {
  await verifyNativeRollbackReadiness(plan, operations)
  const rollback = await snapshotVerifiedRollbackArtifact(plan, operations)
  let candidate: NativeArtifactSnapshot | undefined
  try {
    if (isWatchPlan(plan)) candidate = await snapshotVerifiedCandidateArtifact(plan, operations)
  } catch (error) {
    await rollback.dispose().catch(() => undefined)
    throw error
  }
  let disposed = false
  return {
    rollback,
    ...(candidate === undefined ? {} : { candidate }),
    dispose: async () => {
      if (disposed) return
      disposed = true
      const results = await Promise.allSettled([
        rollback.dispose(),
        ...(candidate === undefined ? [] : [candidate.dispose()]),
      ])
      const errors: unknown[] = []
      for (const result of results) {
        if (result.status === 'rejected') errors.push(result.reason)
      }
      if (errors.length > 0) throw new AggregateError(errors, 'native rollback worker could not remove private installer snapshots')
    },
  }
}

async function terminateJournalCandidate(
  state: NativeUpdateWatchState,
  timeoutMs: number,
  operations: NativeRollbackOperations,
): Promise<void> {
  const candidate = state.candidateProcess
  if (candidate === undefined || !operations.isProcessAlive(candidate)) return
  await terminateCandidateBeforeRollback(candidate, timeoutMs, operations)
}

/** Stop an unhealthy candidate within a finite configured window before any stable bytes are restored. */
async function terminateCandidateBeforeRollback(
  candidate: NativeProcessReference,
  timeoutMs: number,
  operations: NativeRollbackOperations,
): Promise<void> {
  operations.terminate(candidate)
  if (await waitForParentExitBeforeCandidate(candidate, timeoutMs, operations)) return
  operations.forceTerminate(candidate)
  if (await waitForParentExitBeforeCandidate(candidate, timeoutMs, operations)) return
  throw new Error('native update watchdog could not stop the unhealthy candidate')
}

/**
 * Validate an untrusted JSON worker argument before it names any local process or path.
 * @param value - parsed worker argument.
 * @returns the fixed-format plan, or undefined when the argument is invalid.
 */
export function parseNativeRollbackPlan(value: unknown): NativeRollbackPlan | undefined {
  if (!isRecord(value) || !hasExactKeys(value, [
    'schemaVersion', 'platform', 'parentProcess', 'applicationPath', 'rollbackArtifactPath', 'rollbackSha256', 'rollbackFormat', 'healthCheckTimeoutMs',
  ], ['appImagePath', 'candidateArtifactPath', 'candidateSha256', 'candidateFormat', 'journalPath', 'candidateVersion', 'transactionId'])) return undefined
  if (value.schemaVersion !== 1 || !isNativePlatform(value.platform) || !isNativeProcessReference(value.parentProcess, value.platform)
    || typeof value.applicationPath !== 'string' || typeof value.rollbackArtifactPath !== 'string'
    || typeof value.rollbackSha256 !== 'string' || !isRollbackFormat(value.rollbackFormat) || !isBoundedTimeout(value.healthCheckTimeoutMs)
    || (value.appImagePath !== undefined && typeof value.appImagePath !== 'string')) return undefined
  const plan: NativeRollbackPlan = {
    schemaVersion: 1,
    platform: value.platform,
    parentProcess: value.parentProcess,
    applicationPath: value.applicationPath,
    rollbackArtifactPath: value.rollbackArtifactPath,
    rollbackSha256: value.rollbackSha256,
    rollbackFormat: value.rollbackFormat,
    healthCheckTimeoutMs: value.healthCheckTimeoutMs,
    ...(value.appImagePath === undefined ? {} : { appImagePath: value.appImagePath }),
    ...(value.transactionId === undefined ? {} : { transactionId: value.transactionId as string }),
  }
  try {
    validatePlan(plan)
    return plan
  } catch {
    return undefined
  }
}

/**
 * Validate a detached watchdog's JSON argument before it reads a private journal or executes a local installer.
 * @param value - parsed worker argument.
 * @returns fixed watchdog request, or undefined when any field is outside the narrow worker grammar.
 */
export function parseNativeUpdateWatchPlan(value: unknown): NativeUpdateWatchPlan | undefined {
  const rollback = parseNativeRollbackPlan(value)
  if (rollback === undefined || !isRecord(value)
    || typeof value.candidateArtifactPath !== 'string' || !isPlanPathAbsolute(rollback, value.candidateArtifactPath)
    || typeof value.candidateSha256 !== 'string' || !/^[0-9a-f]{64}$/u.test(value.candidateSha256)
    || !isRollbackFormat(value.candidateFormat)
    || typeof value.journalPath !== 'string' || !isPlanPathAbsolute(rollback, value.journalPath)
    || typeof value.candidateVersion !== 'string' || !isSemanticVersion(value.candidateVersion)
    || typeof value.transactionId !== 'string' || !isUuid(value.transactionId)) return undefined
  const plan: NativeUpdateWatchPlan = {
    ...rollback,
    candidateArtifactPath: value.candidateArtifactPath,
    candidateSha256: value.candidateSha256,
    candidateFormat: value.candidateFormat,
    journalPath: value.journalPath,
    candidateVersion: value.candidateVersion,
    transactionId: value.transactionId,
  }
  try {
    validateWatchPlan(plan)
    return plan
  } catch {
    return undefined
  }
}

async function verifyRollbackArtifact(plan: NativeRollbackPlan, operations: NativeRollbackOperations): Promise<void> {
  await verifiedArtifactBytes(plan.rollbackArtifactPath, plan.rollbackSha256, 'native rollback', operations)
}

async function verifyCandidateArtifact(plan: NativeUpdateWatchPlan, operations: NativeRollbackOperations): Promise<void> {
  await verifiedArtifactBytes(plan.candidateArtifactPath, plan.candidateSha256, 'native candidate', operations)
}

async function snapshotVerifiedRollbackArtifact(
  plan: NativeRollbackPlan,
  operations: NativeRollbackOperations,
): Promise<NativeArtifactSnapshot> {
  const bytes = await verifiedArtifactBytes(plan.rollbackArtifactPath, plan.rollbackSha256, 'native rollback', operations)
  return await operations.snapshotArtifact(plan.rollbackArtifactPath, bytes)
}

async function snapshotVerifiedCandidateArtifact(
  plan: NativeUpdateWatchPlan,
  operations: NativeRollbackOperations,
): Promise<NativeArtifactSnapshot> {
  const bytes = await verifiedArtifactBytes(plan.candidateArtifactPath, plan.candidateSha256, 'native candidate', operations)
  return await operations.snapshotArtifact(plan.candidateArtifactPath, bytes)
}

async function verifiedArtifactBytes(
  path: string,
  expectedDigest: string,
  label: string,
  operations: NativeRollbackOperations,
): Promise<Uint8Array> {
  const details = await operations.stat(path)
  if (!details.isFile()) throw new Error(`${label} artifact is not a file`)
  const bytes = await operations.readArtifact(path)
  if (createHash('sha256').update(bytes).digest('hex') !== expectedDigest) {
    throw new Error(`${label} artifact digest changed`)
  }
  return bytes
}

/** Prove the detached worker can create and clean a same-volume private replacement probe before Main exits. */
async function verifyNativeInstallationDestination(
  plan: NativeRollbackPlan | NativeUpdateWatchPlan,
  operations: NativeRollbackOperations,
): Promise<void> {
  if (plan.platform === 'win32') return
  const destinationParent = plan.platform === 'darwin'
    ? posix.dirname(macApplicationBundle(plan.applicationPath))
    : linuxInstallationParent(plan)
  const targetPath = nativePath(plan.platform)
  let probeDirectory = await operations.mkdtemp(targetPath.join(destinationParent, '.harness-desktop-update-probe-'))
  try {
    if (plan.platform === 'linux') {
      const source = isWatchPlan(plan) ? plan.candidateArtifactPath : plan.rollbackArtifactPath
      const probe = targetPath.join(probeDirectory, 'candidate.AppImage')
      await operations.copyFile(source, probe)
      await operations.chmod(probe, 0o755)
    }
    const renamedProbe = `${probeDirectory}.rename`
    await operations.rename(probeDirectory, renamedProbe)
    probeDirectory = renamedProbe
  } finally {
    await operations.remove(probeDirectory)
  }
}

/** @returns the validated writable parent directory for a Linux AppImage replacement. */
function linuxInstallationParent(plan: NativeRollbackPlan | NativeUpdateWatchPlan): string {
  if (plan.platform !== 'linux' || plan.appImagePath === undefined) {
    throw new Error('native rollback Linux installation path is absent')
  }
  return posix.dirname(plan.appImagePath)
}

/** Install an authenticated candidate outside Main, then return its exact new-process identity. */
async function installNativeCandidate(
  plan: NativeUpdateWatchPlan,
  operations: NativeRollbackOperations,
  prepared?: NativeArtifactSnapshot,
): Promise<NativeProcessReference | undefined> {
  const candidate = prepared ?? await snapshotVerifiedCandidateArtifact(plan, operations)
  try {
    if (plan.platform === 'win32') {
      await operations.run(candidate.path, ['/S'])
      return operations.launch(plan.applicationPath)
    }
    if (plan.platform === 'darwin') {
      if (!await replaceMacZip(candidate.path, plan.applicationPath, false, operations)) return undefined
      return operations.launch(plan.applicationPath)
    }
    if (!await replaceLinuxAppImage(candidate.path, plan, operations)) return undefined
    return operations.launch(plan.appImagePath ?? plan.applicationPath)
  } finally {
    if (prepared === undefined) await candidate.dispose()
  }
}

async function waitForParentExit(
  process: NativeProcessReference,
  timeoutMs: number,
  operations: NativeRollbackOperations,
): Promise<boolean> {
  if (await waitForParentExitBeforeCandidate(process, timeoutMs, operations)) return true
  operations.terminate(process)
  if (await waitForParentExitBeforeCandidate(process, timeoutMs, operations)) return true
  operations.forceTerminate(process)
  return await waitForParentExitBeforeCandidate(process, timeoutMs, operations)
}

/** @returns whether the current installation exited before the policy-selected safe handoff deadline. */
async function waitForParentExitBeforeCandidate(
  process: NativeProcessReference,
  timeoutMs: number,
  operations: NativeRollbackOperations,
): Promise<boolean> {
  const deadline = operations.now() + timeoutMs
  while (operations.isProcessAlive(process)) {
    if (operations.now() >= deadline) return false
    await operations.delay(parentExitPollMs)
  }
  return true
}

async function restoreMacZip(archivePath: string, applicationPath: string, operations: NativeRollbackOperations): Promise<void> {
  if (!await replaceMacZip(archivePath, applicationPath, true, operations)) {
    throw new Error('native rollback could not replace the current macOS application')
  }
}

async function replaceMacZip(
  archivePath: string,
  applicationPath: string,
  allowMissingDestination: boolean,
  operations: NativeRollbackOperations,
): Promise<boolean> {
  const appBundle = macApplicationBundle(applicationPath)
  const parent = posix.dirname(appBundle)
  const staging = await operations.mkdtemp(posix.join(parent, '.harness-desktop-rollback-'))
  try {
    await operations.run('/usr/bin/ditto', ['-x', '-k', archivePath, staging])
    const entries = await operations.readdir(staging)
    const bundles = entries.filter(entry => entry.isDirectory() && entry.name.endsWith('.app'))
    if (bundles.length !== 1 || bundles[0] === undefined) throw new Error('native rollback zip does not contain exactly one application bundle')
    return await replaceMacApplication(posix.join(staging, bundles[0].name), appBundle, allowMissingDestination, operations)
  } finally {
    await operations.remove(staging)
  }
}

async function restoreLinuxAppImage(
  artifactPath: string,
  plan: NativeRollbackPlan,
  operations: NativeRollbackOperations,
): Promise<void> {
  if (!await replaceLinuxAppImage(artifactPath, plan, operations)) {
    throw new Error('native rollback could not replace the current AppImage')
  }
}

async function replaceLinuxAppImage(
  artifactPath: string,
  plan: Pick<NativeRollbackPlan, 'appImagePath'>,
  operations: NativeRollbackOperations,
): Promise<boolean> {
  const destination = plan.appImagePath
  if (destination === undefined) throw new Error('native rollback AppImage path is absent')
  const temporary = `${destination}.rollback-${randomUUID()}`
  try {
    await operations.copyFile(artifactPath, temporary)
    await operations.chmod(temporary, 0o755)
    try {
      await operations.rename(temporary, destination)
      return true
    } catch {
      // POSIX rename either publishes the whole candidate or leaves the live AppImage untouched.
      return false
    }
  } finally {
    await operations.remove(temporary)
  }
}

async function replaceMacApplication(
  replacement: string,
  destination: string,
  allowMissingDestination: boolean,
  operations: NativeRollbackOperations,
): Promise<boolean> {
  const retained = posix.join(posix.dirname(destination), '.harness-desktop-retained.app')
  await operations.remove(retained).catch(() => {
    // A previous atomic replacement may leave only its deterministic backup; the fixed destination remains launchable.
  })
  try {
    await operations.run('/usr/bin/osascript', [
      '-l', 'JavaScript', '-e', macAtomicReplacementProgram,
      destination, replacement, basename(retained),
    ])
  } catch (_error) {
    if (!allowMissingDestination) return false
    try {
      await operations.rename(replacement, destination)
      return true
    } catch {
      return false
    }
  }
  await operations.remove(retained).catch(() => {
    // Atomic replacement already left a complete fixed destination; the deterministic backup is recoverable residue.
  })
  return true
}

const macAtomicReplacementProgram = String.raw`
ObjC.import('Foundation')
function run(argv) {
  const manager = $.NSFileManager.defaultManager
  const error = Ref()
  const result = manager.replaceItemAtURLWithItemAtURLBackupItemNameOptionsResultingItemURLError(
    $.NSURL.fileURLWithPath(argv[0]),
    $.NSURL.fileURLWithPath(argv[1]),
    $(argv[2]),
    0,
    null,
    error,
  )
  if (!result) {
    const message = error[0] ? ObjC.unwrap(error[0].localizedDescription) : 'unknown replacement failure'
    throw new Error(message)
  }
}
`

/** @returns the untouched current installation after a candidate replacement fails before publication. */
function stableApplicationPath(plan: NativeUpdateWatchPlan): string {
  return plan.platform === 'linux' ? plan.appImagePath ?? plan.applicationPath : plan.applicationPath
}

function validatePlan(plan: NativeRollbackPlan): void {
  if (
    !isNativeProcessReference(plan.parentProcess, plan.platform)
    || !isPlanPathAbsolute(plan, plan.applicationPath)
    || !isPlanPathAbsolute(plan, plan.rollbackArtifactPath)
    || !/^[0-9a-f]{64}$/u.test(plan.rollbackSha256)
    || !isBoundedTimeout(plan.healthCheckTimeoutMs)
    || (plan.transactionId !== undefined && !isUuid(plan.transactionId))
  ) {
    throw new Error('native rollback plan is invalid')
  }
  if (plan.platform === 'win32') {
    if (plan.rollbackFormat !== 'nsis' || !plan.applicationPath.endsWith('.exe') || !plan.rollbackArtifactPath.endsWith('.exe')) {
      throw new Error('native rollback Windows plan is invalid')
    }
    return
  }
  if (plan.platform === 'darwin') {
    if (plan.rollbackFormat !== 'zip' || !plan.rollbackArtifactPath.endsWith('.zip')) {
      throw new Error('native rollback macOS plan is invalid')
    }
    void macApplicationBundle(plan.applicationPath)
    return
  }
  if (plan.rollbackFormat !== 'appimage' || plan.appImagePath === undefined || !isPlanPathAbsolute(plan, plan.appImagePath)
    || plan.parentProcess.linuxStartTicks === undefined
    || !plan.rollbackArtifactPath.endsWith('.AppImage')) {
    throw new Error('native rollback Linux plan is invalid')
  }
}

function validateWatchPlan(plan: NativeUpdateWatchPlan): void {
  validatePlan(plan)
  if (!isPlanPathAbsolute(plan, plan.candidateArtifactPath) || !/^[0-9a-f]{64}$/u.test(plan.candidateSha256)
    || plan.candidateFormat !== plan.rollbackFormat || !nativeArtifactPathMatches(plan.candidateArtifactPath, plan.candidateFormat)
    || !isPlanPathAbsolute(plan, plan.journalPath) || !isSemanticVersion(plan.candidateVersion) || !isUuid(plan.transactionId)) {
    throw new Error('native update watchdog plan is invalid')
  }
}

function nativeArtifactPathMatches(path: string, format: NativeUpdateWatchPlan['candidateFormat']): boolean {
  if (format === 'nsis') return path.endsWith('.exe')
  if (format === 'zip') return path.endsWith('.zip')
  return path.endsWith('.AppImage')
}

function macApplicationBundle(applicationPath: string): string {
  const macosDirectory = posix.dirname(applicationPath)
  const contentsDirectory = posix.dirname(macosDirectory)
  const bundle = posix.dirname(contentsDirectory)
  if (basename(macosDirectory) !== 'MacOS' || basename(contentsDirectory) !== 'Contents' || !bundle.endsWith('.app')) {
    throw new Error('native rollback macOS application path is invalid')
  }
  return bundle
}

function basename(path: string): string { return path.replace(/[\\/]+$/u, '').split(/[\\/]/u).at(-1) ?? '' }

function nativePath(platform: NativeRollbackPlan['platform']): typeof posix {
  return platform === 'win32' ? win32 : posix
}

function isPlanPathAbsolute(plan: Pick<NativeRollbackPlan, 'platform'>, path: string): boolean {
  return nativePath(plan.platform).isAbsolute(path)
}

function isNativePlatform(value: unknown): value is NativeRollbackPlan['platform'] {
  return value === 'win32' || value === 'darwin' || value === 'linux'
}

function isRollbackFormat(value: unknown): value is NativeRollbackPlan['rollbackFormat'] {
  return value === 'nsis' || value === 'zip' || value === 'appimage'
}

function isPositiveInteger(value: unknown): value is number { return typeof value === 'number' && Number.isSafeInteger(value) && value > 0 }
function isLinuxStartTicks(value: unknown): value is string { return typeof value === 'string' && /^[0-9]{1,32}$/u.test(value) }

function isBoundedTimeout(value: unknown): value is number {
  return typeof value === 'number' && Number.isSafeInteger(value) && value >= 30_000 && value <= 600_000
}

function isSemanticVersion(value: unknown): value is string {
  return typeof value === 'string' && /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/u.test(value)
}

function isUuid(value: unknown): value is string {
  return typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(value)
}

function isWatchPlan(plan: NativeRollbackPlan | NativeUpdateWatchPlan): plan is NativeUpdateWatchPlan {
  return 'journalPath' in plan
}

/**
 * Resolve the only readiness marker a native watchdog may accept for an external recovery worker.
 * @param rollbackArtifactPath - verified artifact beneath the private native-update cache.
 * @param workerId - one unguessable recovery-worker identifier.
 * @param platform - target platform that owns the cache path.
 * @returns absolute marker path outside the application installation.
 */
export function nativeRollbackReadyPath(
  rollbackArtifactPath: string,
  workerId: string,
  platform: NativeRollbackPlan['platform'],
): string {
  return nativeUpdateWorkerPath(rollbackArtifactPath, `native-rollback-ready-${workerId}.json`, platform)
}

/** Redacted stages that a Windows recovery worker may report before it arms a native transition. */
export type NativeRollbackWorkerFailurePhase =
  | 'validating'
  | 'snapshotting-rollback'
  | 'snapshotting-candidate'
  | 'waiting-parent'
  | 'watching-candidate'
  | 'rolling-back'

/**
 * Resolve the cache-local failure receipt written only when a Windows worker cannot arm before Main exits.
 * @param rollbackArtifactPath - verified artifact beneath the private native-update cache.
 * @param workerId - one unguessable recovery-worker identifier.
 * @param platform - target platform that owns the cache path.
 * @returns absolute redacted failure-receipt path outside the application installation.
 */
export function nativeRollbackWorkerFailurePath(
  rollbackArtifactPath: string,
  workerId: string,
  platform: NativeRollbackPlan['platform'],
): string {
  return nativeUpdateWorkerPath(rollbackArtifactPath, `native-rollback-failure-${workerId}.json`, platform)
}

/**
 * @param rollbackArtifactPath - verified cache artifact path.
 * @param transactionId - completed update transaction.
 * @param platform - target platform that owns the cache path.
 * @returns the transaction-specific marker written only after a watchdog observes the applied journal state.
 */
export function nativeUpdateAppliedPath(
  rollbackArtifactPath: string,
  transactionId: string,
  platform: NativeRollbackPlan['platform'],
): string {
  return nativeUpdateWorkerPath(rollbackArtifactPath, `native-update-applied-${transactionId}.json`, platform)
}

/**
 * @param rollbackArtifactPath - verified cache artifact path.
 * @param transactionId - recovered update transaction.
 * @param platform - target platform that owns the cache path.
 * @returns the transaction-specific marker written after the watchdog restores the retained release and before stable launch.
 */
export function nativeUpdateRolledBackPath(
  rollbackArtifactPath: string,
  transactionId: string,
  platform: NativeRollbackPlan['platform'],
): string {
  return nativeUpdateWorkerPath(rollbackArtifactPath, `native-update-rolled-back-${transactionId}.json`, platform)
}

/**
 * @param rollbackArtifactPath - verified cache artifact path.
 * @param transactionId - active update transaction.
 * @param platform - target platform that owns the cache path.
 * @returns a transaction-specific freshness record written only after the external worker launches the candidate.
 */
export function nativeUpdateHeartbeatPath(
  rollbackArtifactPath: string,
  transactionId: string,
  platform: NativeRollbackPlan['platform'],
): string {
  return nativeUpdateWorkerPath(rollbackArtifactPath, `native-update-heartbeat-${transactionId}.json`, platform)
}

/** Write the one post-launch liveness proof that a candidate Main must observe before it opens the Dashboard. */
async function writeNativeWatchHeartbeat(plan: NativeUpdateWatchPlan, operations: NativeRollbackOperations): Promise<void> {
  await operations.writeWatchHeartbeat(
    nativeUpdateHeartbeatPath(plan.rollbackArtifactPath, plan.transactionId, plan.platform),
    `${plan.transactionId}:${String(Date.now())}\n`,
  )
}

function nativeUpdateWorkerPath(
  rollbackArtifactPath: string,
  filename: string,
  platform: NativeRollbackPlan['platform'],
): string {
  const path = nativePath(platform)
  return path.join(path.dirname(path.dirname(rollbackArtifactPath)), 'workers', filename)
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype
}

function hasExactKeys(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): boolean {
  const allowed = new Set([...required, ...optional])
  return Object.keys(value).every(key => allowed.has(key)) && required.every(key => Object.hasOwn(value, key))
}

function childExit(child: ChildProcess): Promise<void> {
  return new Promise((resolve, reject) => {
    child.once('error', reject)
    child.once('exit', (code, signal) => {
      if (code === 0) resolve()
      else reject(new Error(`native rollback command exited with ${code === null ? signal ?? 'unknown status' : String(code)}`))
    })
  })
}

async function readNativeUpdateWatchState(path: string): Promise<NativeUpdateWatchState | undefined> {
  let text: string
  try {
    text = new TextDecoder('utf-8', { fatal: true }).decode(await readNativePrivateRegularBytes(path, 'native update watchdog journal'))
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw new Error('native update watchdog journal cannot be read', { cause: error })
  }
  let value: unknown
  try {
    value = JSON.parse(text) as unknown
  } catch {
    throw new Error('native update watchdog journal is malformed')
  }
  const state = parseNativeUpdateWatchState(value)
  if (state === undefined) throw new Error('native update watchdog journal is invalid')
  return state
}

/**
 * Parse the private native-install journal fields a detached watchdog must observe.
 * @param value - decoded persisted journal object.
 * @returns the bounded watchdog state, or undefined for an unsupported journal representation.
 */
export function parseNativeUpdateWatchState(value: unknown): NativeUpdateWatchState | undefined {
  if (!isRecord(value) || !hasExactKeys(value, [
    'schemaVersion', 'transactionId', 'phase', 'currentVersion', 'version', 'channel', 'format', 'sha256', 'rollbackFormat', 'rollbackSha256',
  ], ['candidateProcess']) || value.schemaVersion !== 1 || !isSemanticVersion(value.version) || !isUuid(value.transactionId)
    || (value.phase !== 'awaiting-dashboard-health' && value.phase !== 'dashboard-health-checking' && value.phase !== 'rollback-scheduled' && value.phase !== 'applied')
    || (value.candidateProcess !== undefined && !isNativeProcessReference(value.candidateProcess))) {
    return undefined
  }
  if (((value.phase === 'dashboard-health-checking' || value.phase === 'rollback-scheduled') && value.candidateProcess === undefined)
    || (value.phase === 'awaiting-dashboard-health' && value.candidateProcess !== undefined)) {
    return undefined
  }
  return {
    phase: value.phase,
    version: value.version,
    transactionId: value.transactionId,
    ...(value.candidateProcess === undefined ? {} : { candidateProcess: value.candidateProcess }),
  }
}

/** Read one cache-local regular file through a stable no-follow handle before its bytes influence an installer. */
async function readNativePrivateRegularBytes(path: string, label: string): Promise<Buffer> {
  const before = await lstat(path)
  if (!before.isFile() || before.isSymbolicLink() || before.nlink !== 1) {
    throw new Error(`${label} is not a private regular file`)
  }
  const handle = await open(path, process.platform === 'win32'
    ? constants.O_RDONLY
    : constants.O_RDONLY | constants.O_NOFOLLOW)
  try {
    const opened = await handle.stat()
    const after = await lstat(path)
    if (!opened.isFile() || !after.isFile() || after.isSymbolicLink() || opened.nlink !== 1
      || !sameNativeFile(before, opened) || !sameNativeFile(opened, after)) {
      throw new Error(`${label} changed while opening`)
    }
    return await handle.readFile()
  } finally {
    await handle.close()
  }
}

function sameNativeFile(left: Stats, right: Stats): boolean {
  return left.dev === right.dev && left.ino === right.ino && left.nlink === right.nlink
}

/** Write verified bytes into an exclusive private worker directory so later execution never reopens cache paths. */
async function snapshotNativeArtifact(sourcePath: string, bytes: Uint8Array): Promise<NativeArtifactSnapshot> {
  const directory = await mkdtemp(join(tmpdir(), 'harness-desktop-native-artifact-'))
  const path = join(directory, `installer${extname(sourcePath)}`)
  try {
    await writeFile(path, bytes, { flag: 'wx', mode: 0o600 })
  } catch (error) {
    await rm(directory, { recursive: true, force: true })
    throw error
  }
  return {
    path,
    dispose: async () => { await rm(directory, { recursive: true, force: true }) },
  }
}

/** Durably publish one exclusive transaction marker without following an existing name. */
async function writeNativeWatchMarkerFile(path: string, content: string): Promise<void> {
  const temporary = `${path}.staging-${randomUUID()}`
  try {
    const existing = await lstat(path).then(() => true, (error: unknown) => {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false
      throw error
    })
    if (existing) throw new Error('native update watchdog heartbeat already exists')
    const handle = await open(temporary, 'wx', 0o600)
    try {
      await handle.writeFile(content)
      await handle.sync()
    } finally {
      await handle.close()
    }
    await rename(temporary, path)
    await syncNativeDirectory(dirname(path))
  } finally {
    await rm(temporary, { force: true })
  }
}

/** Persist one private directory entry that a candidate restart uses to distinguish a live worker from stale recovery state. */
async function syncNativeDirectory(path: string): Promise<void> {
  const handle = await open(path, process.platform === 'win32' ? 'a+' : constants.O_RDONLY)
  try {
    await handle.sync()
  } finally {
    await handle.close()
  }
}

function nativeRun(command: string, args: readonly string[]): Promise<void> {
  return childExit(spawn(command, args, { windowsHide: true, stdio: 'ignore' }))
}

function nativeLaunch(command: string): NativeProcessReference {
  const environment = { ...process.env }
  delete environment.ELECTRON_RUN_AS_NODE
  const child = spawn(command, [], { detached: true, stdio: 'ignore', windowsHide: true, env: environment })
  if (child.pid === undefined) throw new Error('native rollback worker could not identify the candidate process')
  const linuxStartTicks = process.platform === 'linux' ? linuxProcessStartTicks(child.pid) : undefined
  if (process.platform === 'linux' && linuxStartTicks === undefined) {
    child.kill('SIGKILL')
    throw new Error('native rollback worker could not bind the Linux candidate process identity')
  }
  const reference: NativeProcessReference = {
    processId: child.pid,
    executablePath: command,
    startedBeforeMs: Date.now(),
    ...(linuxStartTicks === undefined ? {} : { linuxStartTicks }),
    ...(process.platform === 'win32' ? {} : { processGroupId: child.pid }),
  }
  child.unref()
  return reference
}

const currentLinuxStartTicks = process.platform === 'linux' ? linuxProcessStartTicks(process.pid) : undefined
const currentProcessReference: NativeProcessReference = Object.freeze({
  processId: process.pid,
  executablePath: process.execPath,
  startedBeforeMs: Math.ceil(Date.now() - process.uptime() * 1000),
  ...(currentLinuxStartTicks === undefined ? {} : { linuxStartTicks: currentLinuxStartTicks }),
})

/** @returns the immutable identity for this one Main process, including its startup bound. */
export function currentNativeProcessReference(): NativeProcessReference { return currentProcessReference }

/** @param value - decoded process reference. @returns whether the reference has the exact trusted worker grammar. */
export function isNativeProcessReference(
  value: unknown,
  platform?: NativeRollbackPlan['platform'],
): value is NativeProcessReference {
  return isRecord(value) && hasExactKeys(value, ['processId', 'executablePath', 'startedBeforeMs'], ['linuxStartTicks', 'processGroupId'])
    && isPositiveInteger(value.processId) && typeof value.executablePath === 'string'
    && (platform === undefined ? isAbsolute(value.executablePath) : nativePath(platform).isAbsolute(value.executablePath))
    && typeof value.startedBeforeMs === 'number' && Number.isSafeInteger(value.startedBeforeMs) && value.startedBeforeMs > 0
    && (value.linuxStartTicks === undefined || isLinuxStartTicks(value.linuxStartTicks))
    && (value.processGroupId === undefined || (isPositiveInteger(value.processGroupId) && value.processGroupId === value.processId))
}

function nativeProcessIsAlive(reference: NativeProcessReference): boolean {
  if (process.platform !== 'win32' && reference.processGroupId !== undefined) {
    try {
      process.kill(-reference.processGroupId, 0)
      return true
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ESRCH') return false
      throw new Error('native rollback worker cannot inspect the expected process group')
    }
  }
  try {
    process.kill(reference.processId, 0)
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ESRCH') return false
    throw new Error('native rollback worker cannot inspect the expected process')
  }
  if (process.platform === 'win32') {
    throw new Error('Windows native rollback must use its external identity-aware worker')
  }
  return process.platform === 'linux' ? linuxProcessMatches(reference) : posixProcessMatches(reference)
}

/** Bind a checking or atomically applied health report to the process launched by this detached worker. */
function matchesLaunchedCandidate(
  platform: NativeRollbackPlan['platform'],
  launched: NativeProcessReference,
  reported: NativeProcessReference,
): boolean {
  if (launched.processId !== reported.processId) return false
  if (platform === 'linux') {
    return launched.linuxStartTicks !== undefined && launched.linuxStartTicks === reported.linuxStartTicks
  }
  return launched.executablePath === reported.executablePath && reported.startedBeforeMs <= launched.startedBeforeMs
}

/** Compare Linux processes by the kernel start token because an AppImage changes `/proc/<pid>/exe` after `exec`. */
function linuxProcessMatches(reference: NativeProcessReference): boolean {
  return reference.linuxStartTicks !== undefined && linuxProcessStartTicks(reference.processId) === reference.linuxStartTicks
}

/** @returns Linux `/proc/<pid>/stat` field 22, which uniquely binds a PID until reboot. */
function linuxProcessStartTicks(processId: number): string | undefined {
  let content: string
  try {
    content = readFileSync(`/proc/${String(processId)}/stat`, 'utf8')
  } catch {
    return undefined
  }
  const closingParenthesis = content.lastIndexOf(')')
  if (closingParenthesis === -1) return undefined
  const token = content.slice(closingParenthesis + 1).trim().split(/\s+/u)[19]
  return token !== undefined && isLinuxStartTicks(token) ? token : undefined
}

function posixProcessMatches(reference: NativeProcessReference): boolean {
  const ps = process.platform === 'darwin' ? '/bin/ps' : '/usr/bin/ps'
  let output: string
  try {
    output = execFileSync(ps, ['-p', String(reference.processId), '-o', 'lstart=', '-o', 'args='], {
      encoding: 'utf8',
      env: { LC_ALL: 'C', LANG: 'C' },
      stdio: ['ignore', 'pipe', 'ignore'],
      windowsHide: true,
    })
  } catch {
    return false
  }
  const match = output.trim().match(/^(\w{3}\s+\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}\s+\d{4})\s+(.+)$/u)
  if (match?.[1] === undefined || match[2] === undefined) throw new Error('native rollback worker cannot parse process identity')
  const startedAt = Date.parse(match[1])
  if (!Number.isFinite(startedAt) || startedAt > reference.startedBeforeMs) return false
  return match[2] === reference.executablePath || match[2].startsWith(`${reference.executablePath} `)
}

const nativeRollbackOperations: NativeRollbackOperations = {
  isProcessAlive: nativeProcessIsAlive,
  terminate: (reference) => {
    if (nativeProcessIsAlive(reference)) terminateNativeProcessTree(reference, 'SIGTERM')
  },
  forceTerminate: (reference) => {
    if (nativeProcessIsAlive(reference)) terminateNativeProcessTree(reference, 'SIGKILL')
  },
  now: () => performance.now(),
  delay: milliseconds => new Promise((resolve) => { setTimeout(resolve, milliseconds) }),
  readArtifact: async path => await readNativePrivateRegularBytes(path, 'native installer cache'),
  snapshotArtifact: snapshotNativeArtifact,
  readWatchState: readNativeUpdateWatchState,
  writeWatchHeartbeat: writeNativeWatchMarkerFile,
  writeRollbackCompletion: writeNativeWatchMarkerFile,
  run: nativeRun,
  launch: nativeLaunch,
  mkdtemp,
  readdir: async path => await readdir(path, { withFileTypes: true }),
  rename,
  copyFile,
  chmod,
  stat,
  remove: async (path) => { await rm(path, { recursive: true, force: true }) },
}

/** Kill the detached POSIX process group created for a verified native candidate. */
function terminateNativeProcessTree(reference: NativeProcessReference, signal: NodeJS.Signals): void {
  if (reference.processGroupId === undefined) {
    try { process.kill(reference.processId, signal) } catch {}
    return
  }
  try {
    process.kill(-reference.processGroupId, signal)
  } catch {
    try { process.kill(reference.processId, signal) } catch {}
  }
}
